import Head from "next/head";
import Layout from "@/components/layout/Layout";

import { useChatContext } from "@/lib/ChatContext";

import ChatRoom from "@/components/chatRoom/ChatRoom";
import ChatRoomList from "@/components/chatRoomList/ChatRoomList";

export default function HomePage() {
	const { activeChatId } = useChatContext();

	return (
		<>
			<Head>
				<title>Chat App</title>
				<meta name="description" content="Generated by create next app" />
			</Head>

			{activeChatId ? (
				<ChatRoom />
			) : (
				<Layout>
					<ChatRoomList />
				</Layout>
			)}
		</>
	);
}
