import Head from "next/head";
import Layout from "@/components/layout/Layout";
import ChatRoomList from "@/components/chatRoomList/ChatRoomList";

export default function HomePage() {
	return (
		<>
			<Head>
				<title>Chat App</title>
				<meta name="description" content="Generated by create next app" />
			</Head>

			<Layout>
				<ChatRoomList />
			</Layout>
		</>
	);
}
